### ISSUE TITLE
SP108E won't respond to configuration attempts; remains in AP mode

### ISSUE THREAD

**Issue by rbrenton** [Spled/spled.github.io#2]
Despite my best efforts, I can't seem to configure the device to connect to another wifi AP so that I don't need to connect to the device's built-in AP every time I want to change settings.  I'm on an iPhone XS. Does anyone else have this issue?

**Comment by 0x20004** [comment]
Hey :)
You are not the only one.
I found more people having problems like this in the Google Play Store and Amazon comment section.
But no one has an answer for this.
The best hint was removing the white spaces from the Wifi name what didn't worked for me.
I tested it also with a wifi named "test" an password "12345678" so even any character encoding issues are left out.
Connecting to the AP of the controller works fine.

Any ideas? Maybe it is a failure of the app because i ordered a replacement for the first one and both are having the same problem.

**Comment by rbrenton** [comment]
I started reverse engineering the protocol the app uses to communicate with the controller. If I figure out how to set the wifi settings I'll share it. Whatever the app is doing is not working.

**Comment by 0x20004** [comment]
That's great.

I've contacted the support of BTF-Lightning.
Maybe they will fix a bug in the app. I hope so because the last version was released just a week ago.

I keep you updated.

**Comment by 0x20004** [comment]
Well the answer from BTF-Lightning was that it's actually hard to connect it in STA mode.
They recommended to use 2-3 smartphones with the app installed at the same time to authentificate the controller on our own AP.

**Comment by valleyman86** [comment]
I found I was unable to make this work either. Turns out that I was connected to a network that supports both 2.4ghz and 5ghz using the same SSID (Netgear Orbi). I disabled 5ghz temporarily and it connected fine. After reenabling it the controller continues to connect.

**Comment by rbrenton** [comment]
> I found I was unable to make this work either. Turns out that I was connected to a network that supports both 2.4ghz and 5ghz using the same SSID (Netgear Orbi). I disabled 5ghz temporarily and it connected fine. After reenabling it the controller continues to connect.

This did the trick.  THANK YOU!

**Comment by rbrenton** [comment]
App must be on 2.4ghz network and/or 5ghz disabled on host AP for configuration attempt to work.

**Comment by 0x20004** [comment]
Here i have some more useful information about this problem/solution.
Three weeks ago i already tried to disable the 5Ghz network but it didn't worked.

Yesterday i disabled the 5Ghz again and ran on 2.4Ghz only.
I changed the network name so it's not containing any spaces and changed the password as well so it's not the maximum 64 characters long.

After these changes it connected straight up.
I also noticed that the lightbar is flashing once after powering up.
A second single flash is occuring after some seconds and if the connection to the AP was successful it flashed a third time.

**Comment by dgott1** [comment]
Hi,
Just got a set of two SP-108E controllers.  Trying to connect with an iphone and I have a 2.4ghz router.
Does it work better on android?

**Comment by Zink-Sa** [comment]
Hey also got a pair of two sp108e. Both controller don’t t function properly with my ws2811b led strips. I’m able to connect via Ap or wifi with my iPhone X but every attempt to configure some effects on the controller won’t work. Even simple things like turning on or off.

**Comment by MouloudThug** [comment]
Hi, I bought this controller last week and tier everything to connect it to my

**Comment by jdc85** [comment]
Нашел способ и не важно объедены сети 5 и 2.4 ггц. Самое главное что бы сеть с 2.4ггц.  режим сети был выбран b/g mixed без n (это важно)! И тогда произойдет подключение! Но я на всякий случай отключил 5ггц. (На время подключения), а потом снова объеденил и все ок! Кому помог рад за Вас!

**Comment by jdc85** [comment]
Всё эти манипуляции производил именно с sp108e rev.1. Тот который без кнопки.

**Comment by MouloudThug** [comment]
Ok I needed some traduction but it workded !
I switched my 2.4ghz wifi network from b/g/n to b/g and my sp108e finally successed to connect to my network.
(I also desactivated my 5ghz network during the connection to be sure)
Thanks you so much for your help, you saved me !

**Comment by 0x20004** [comment]
I can confirm that the connection is working now.
I followed your instructions and set the 2.4ghz wifi network from b/g/n to b/g and disable the 5ghz wifi network temporally.

Also i hold the smartphone 20cm near the SP108E device while connecting.
The first few tries in a distance of around 50cm ended up in a "Failed" screen while adding the device in the app.
The access point is right below. Maybe this is a problem.
I don't now. But it working now after years.

**Comment by jdc85** [comment]
I decided to translate for everyone! I found a way and it doesn't matter if the 5 and 2.4 GHz networks are connected. The most important thing is that the network with 2.4GHz. the network mode was selected b/g mixed without n (this is important)! And then the connection will happen! But I turned off 5ghz just in case. (At the time of connection), and then united again and everything is OK! I am happy for you who I helped! All these manipulations were performed with the sp108e rev.1. The one without the button.

**Comment by jdc85** [comment]
Нужно почитать за него, возможно есть расширенные настройки. b/g поддержка для старых устройств. Я свой 4a 100мгб перепрошил на падаван, копия асуса. Появилась куча настроек. Не знаю есть ли на ваш роутер на ядре линукс. Думаю есть. Два минуса заметил. 1й это не возможность управления роутером из приложения сиаоми. И удалённое управление из приложения и др сети. Но это оешаемо(только с приложением не получится от сиалми) сеть 2.4 использую для этого и для дальней связи, а так на 5ке сижу. Советую попробовать может это как-то решит проблему или попробывать скоростью 2.4 канала поиграться и ограничить до 150 мб или до 54. возможно подхватит. 5 и 2.4 разнести на разные имена т.е. что-бы было две сети 5 и 2.4. Возможно вопрос решится. Эта проблема стала у меня именно при переходе с Тп линка на сиаоми. Вот и начал копать в этом направлении. Наткнулся на эту ветку, и после победы над модулем дополнил её.
