### ISSUE TITLE
FairyNest - unable to log in

### ISSUE THREAD

**Issue by carrickcarpenter** [Spled/spled.github.io#7]
Hello,
I'm not able to log into my fairy nest app.  I believe I'm typing in the correct credentials.  However, I tried to reset the password and the application consistently gives the error message, "Failed to Send Pin Code."   Is there any guidance that can be provided?

CC

**Comment by ev911** [comment]
I am having the same issue

**Comment by kpayne14** [comment]
me too been doin it got a couple of days

**Comment by ev911** [comment]
Mine is working now

**Comment by carrickcarpenter** [comment]
Interesting.  Mine is working now as well.  Would love to know what changed but am grateful to have lights again.
